// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArtist = "artist"

// Artist mapped from table <artist>
type Artist struct {
	ID          int32   `gorm:"column:id;type:integer;primaryKey" json:"id"`
	DataQuality *string `gorm:"column:data_quality;type:character varying(100)" json:"data_quality"`
	Name        *string `gorm:"column:name;type:character varying(1000)" json:"name"`
	Profile     *string `gorm:"column:profile;type:text" json:"profile"`
	RealName    *string `gorm:"column:real_name;type:character varying(2000)" json:"real_name"`
}

// TableName Artist's table name
func (*Artist) TableName() string {
	return TableNameArtist
}
