// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/state303/go-discogs/src/reference"
	"github.com/state303/go-discogs/src/types"
)

const TableNameArtistAlias = "artist_alias"

// ArtistAlias mapped from table <artist_alias>
type ArtistAlias struct {
	ArtistID int32 `gorm:"column:artist_id;type:integer;primaryKey" json:"artist_id"`
	AliasID  int32 `gorm:"column:alias_id;type:integer;primaryKey" json:"alias_id"`
}

func (a *ArtistAlias) References() []reference.Reference {
	return []reference.Reference{
		&Reference{a.ArtistID, types.ARTIST},
		&Reference{a.AliasID, types.ARTIST},
	}
}

// TableName ArtistAlias's table name
func (*ArtistAlias) TableName() string {
	return TableNameArtistAlias
}
