// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/state303/go-discogs/src/reference"
	"github.com/state303/go-discogs/src/types"
)

const TableNameArtistGroup = "artist_group"

// ArtistGroup mapped from table <artist_group>
type ArtistGroup struct {
	ArtistID int32 `gorm:"column:artist_id;type:integer;primaryKey" json:"artist_id"`
	GroupID  int32 `gorm:"column:group_id;type:integer;primaryKey" json:"group_id"`
}

func (g *ArtistGroup) References() []reference.Reference {
	return []reference.Reference{
		&Reference{g.ArtistID, types.ARTIST},
		&Reference{g.GroupID, types.ARTIST},
	}
}

// TableName ArtistGroup's table name
func (*ArtistGroup) TableName() string {
	return TableNameArtistGroup
}
