// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArtistNameVariation = "artist_name_variation"

// ArtistNameVariation mapped from table <artist_name_variation>
type ArtistNameVariation struct {
	ArtistID          int32  `gorm:"column:artist_id;type:integer;primaryKey" json:"artist_id"`
	NameVariation     string `gorm:"column:name_variation;type:character varying(2000);not null" json:"name_variation"`
	NameVariationHash int64  `gorm:"column:name_variation_hash;type:bigint;primaryKey" json:"name_variation_hash"` // fnv32 encoded hash from name_variation
}

// TableName ArtistNameVariation's table name
func (*ArtistNameVariation) TableName() string {
	return TableNameArtistNameVariation
}
