// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGenre = "genre"

// Genre mapped from table <genre>
type Genre struct {
	ID   int32  `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;type:character varying(50);not null;uniqueIndex:genre_name_key,priority:1" json:"name"`
}

// TableName Genre's table name
func (*Genre) TableName() string {
	return TableNameGenre
}
