// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLabel = "label"

// Label mapped from table <label>
type Label struct {
	ID          int32   `gorm:"column:id;type:integer;primaryKey" json:"id"`
	ContactInfo *string `gorm:"column:contact_info;type:text" json:"contact_info"`
	DataQuality *string `gorm:"column:data_quality;type:character varying(100)" json:"data_quality"`
	Name        *string `gorm:"column:name;type:character varying(300)" json:"name"`
	Profile     *string `gorm:"column:profile;type:text" json:"profile"`
	ParentID    *int32  `gorm:"column:parent_id;type:integer" json:"parent_id"`
}

// TableName Label's table name
func (*Label) TableName() string {
	return TableNameLabel
}
