// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/state303/go-discogs/src/reference"
	"github.com/state303/go-discogs/src/types"
)

const TableNameLabelRelease = "label_release"

// LabelRelease mapped from table <label_release>
type LabelRelease struct {
	LabelID          int32   `gorm:"column:label_id;type:integer;primaryKey" json:"label_id"`
	ReleaseID        int32   `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	CategoryNotation *string `gorm:"column:category_notation;type:character varying(1000)" json:"category_notation"`
}

func (r *LabelRelease) References() []reference.Reference {
	return []reference.Reference{
		&Reference{r.LabelID, types.LABEL},
	}
}

// TableName LabelRelease's table name
func (*LabelRelease) TableName() string {
	return TableNameLabelRelease
}
