// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMaster = "master"

// Master mapped from table <master>
type Master struct {
	ID            int32   `gorm:"column:id;type:integer;primaryKey" json:"id"`
	DataQuality   *string `gorm:"column:data_quality;type:character varying(100)" json:"data_quality"`
	Title         *string `gorm:"column:title;type:character varying(2000)" json:"title"`
	ReleasedYear  *int16  `gorm:"column:released_year;type:smallint" json:"released_year"`
}

// TableName Master's table name
func (*Master) TableName() string {
	return TableNameMaster
}