// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/state303/go-discogs/src/reference"
	"github.com/state303/go-discogs/src/types"
)

const TableNameMasterArtist = "master_artist"

// MasterArtist mapped from table <master_artist>
type MasterArtist struct {
	ArtistID int32 `gorm:"column:artist_id;type:integer;primaryKey" json:"artist_id"`
	MasterID int32 `gorm:"column:master_id;type:integer;primaryKey" json:"master_id"`
}

func (a *MasterArtist) References() []reference.Reference {
	return []reference.Reference{
		&Reference{a.ArtistID, types.ARTIST},
	}
}

// TableName MasterArtist's table name
func (*MasterArtist) TableName() string {
	return TableNameMasterArtist
}
