// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/state303/go-discogs/src/reference"
	"github.com/state303/go-discogs/src/types"
)

const TableNameMasterStyle = "master_style"

// MasterStyle mapped from table <master_style>
type MasterStyle struct {
	MasterID int32 `gorm:"column:master_id;type:integer;primaryKey" json:"master_id"`
	StyleID  int32 `gorm:"column:style_id;type:integer;primaryKey" json:"style_id"`
}

func (s *MasterStyle) References() []reference.Reference {
	return []reference.Reference{
		&Reference{s.StyleID, types.STYLE},
	}
}

// TableName MasterStyle's table name
func (*MasterStyle) TableName() string {
	return TableNameMasterStyle
}
