// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMasterVideo = "master_video"

// MasterVideo mapped from table <master_video>
type MasterVideo struct {
	MasterID    int32   `gorm:"column:master_id;type:integer;primaryKey" json:"master_id"`
	URLHash     int64   `gorm:"column:url_hash;type:bigint;primaryKey" json:"url_hash"` // fnv32 encoded hash from url
	URL         string  `gorm:"column:url;type:character varying(2048);not null" json:"url"`
	Description *string `gorm:"column:description;type:character varying(4000)" json:"description"`
	Title       *string `gorm:"column:title;type:character varying(1000)" json:"title"`
}

// TableName MasterVideo's table name
func (*MasterVideo) TableName() string {
	return TableNameMasterVideo
}
