// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseFormat = "release_format"

// ReleaseFormat mapped from table <release_format>
type ReleaseFormat struct {
	ReleaseID   int32   `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	Description *string `gorm:"column:description;type:character varying(10000)" json:"description"`
	Name        *string `gorm:"column:name;type:character varying(255)" json:"name"`
	Quantity    *int32  `gorm:"column:quantity;type:integer" json:"quantity"`
	Text        *string `gorm:"column:text;type:character varying(5000)" json:"text"`
	FormatHash  int64   `gorm:"column:format_hash;type:bigint;primaryKey" json:"format_hash"` // fnv32 encoded hash from string which is description, name, quantity, text appended in order
}

// TableName ReleaseFormat's table name
func (*ReleaseFormat) TableName() string {
	return TableNameReleaseFormat
}
