// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseImage = "release_image"

// ReleaseImage mapped from table <release_image>
type ReleaseImage struct {
	ReleaseID int32  `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	URLHash   int64  `gorm:"column:url_hash;type:bigint;primaryKey" json:"url_hash"` // fnv32 encoded hash from url
	URL       string `gorm:"column:url;type:character varying(2048);not null" json:"url"`
}

// TableName ReleaseImage's table name
func (*ReleaseImage) TableName() string {
	return TableNameReleaseImage
}
