// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseTrack = "release_track"

// ReleaseTrack mapped from table <release_track>
type ReleaseTrack struct {
	ReleaseID int32   `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	Duration  *string `gorm:"column:duration;type:character varying(1500)" json:"duration"`
	Position  *string `gorm:"column:position;type:character varying(1500)" json:"position"`
	Title     *string `gorm:"column:title;type:character varying(10000)" json:"title"`
	TitleHash int64   `gorm:"column:title_hash;type:bigint;primaryKey" json:"title_hash"` // fnv32 encoded hash from title
}

// TableName ReleaseTrack's table name
func (*ReleaseTrack) TableName() string {
	return TableNameReleaseTrack
}
