// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseVideo = "release_video"

// ReleaseVideo mapped from table <release_video>
type ReleaseVideo struct {
	ReleaseID   int32   `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	Description *string `gorm:"column:description;type:character varying(4000)" json:"description"`
	Title       *string `gorm:"column:title;type:character varying(1000)" json:"title"`
	URL         string  `gorm:"column:url;type:character varying(2048);not null" json:"url"`
	URLHash     int64   `gorm:"column:url_hash;type:bigint;primaryKey" json:"url_hash"` // fnv32 encoded hash from url
}

// TableName ReleaseVideo's table name
func (*ReleaseVideo) TableName() string {
	return TableNameReleaseVideo
}
