// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseStyle = "release_style"

// ReleaseStyle mapped from table <release_style>
type ReleaseStyle struct {
	ReleaseID int32 `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	StyleID   int32 `gorm:"column:style_id;type:integer;primaryKey" json:"style_id"`
}

// TableName ReleaseStyle's table name
func (*ReleaseStyle) TableName() string {
	return TableNameReleaseStyle
}
