// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseGenre = "release_genre"

// ReleaseGenre mapped from table <release_genre>
type ReleaseGenre struct {
	ReleaseID int32 `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	GenreID   int32 `gorm:"column:genre_id;type:integer;primaryKey" json:"genre_id"`
}

// TableName ReleaseGenre's table name
func (*ReleaseGenre) TableName() string {
	return TableNameReleaseGenre
}
