// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseContract = "release_contract"

// ReleaseContract mapped from table <release_contract>
type ReleaseContract struct {
	ReleaseID    int32  `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	LabelID      int32  `gorm:"column:label_id;type:integer;primaryKey" json:"label_id"`
	ContractHash int64  `gorm:"column:contract_hash;type:bigint;primaryKey" json:"contract_hash"` // fnv32 encoded hash from contract
	Contract     string `gorm:"column:contract;type:character varying(5000);not null" json:"contract"`
}

// TableName ReleaseContract's table name
func (*ReleaseContract) TableName() string {
	return TableNameReleaseContract
}
