// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseArtist = "release_artist"

// ReleaseArtist mapped from table <release_artist>
type ReleaseArtist struct {
	ReleaseID int32 `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	ArtistID  int32 `gorm:"column:artist_id;type:integer;primaryKey" json:"artist_id"`
}

// TableName ReleaseArtist's table name
func (*ReleaseArtist) TableName() string {
	return TableNameReleaseArtist
}
