// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelease = "release"

// Release mapped from table <release>
type Release struct {
	ID                int32   `gorm:"column:id;type:integer;primaryKey" json:"id"`
	Title             *string `gorm:"column:title;type:character varying(10000)" json:"title"`
	Country           *string `gorm:"column:country;type:character varying(100)" json:"country"`
	DataQuality       *string `gorm:"column:data_quality;type:character varying(100)" json:"data_quality"`
	ReleasedYear      *int16  `gorm:"column:released_year;type:smallint" json:"released_year"`
	ReleasedMonth     *int16  `gorm:"column:released_month;type:smallint" json:"released_month"`
	ReleasedDay       *int16  `gorm:"column:released_day;type:smallint" json:"released_day"`
	ListedReleaseDate *string `gorm:"column:listed_release_date;type:character varying(255)" json:"listed_release_date"`
	MasterID          *int32  `gorm:"column:master_id;type:integer" json:"master_id"`
	IsMaster          *bool   `gorm:"column:is_master;type:boolean" json:"is_master"`
	Notes             *string `gorm:"column:notes;type:text" json:"notes"`
	Status            *string `gorm:"column:status;type:character varying(255)" json:"status"`
}

// TableName Release's table name
func (*Release) TableName() string {
	return TableNameRelease
}
