// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReleaseIdentifier = "release_identifier"

// ReleaseIdentifier mapped from table <release_identifier>
type ReleaseIdentifier struct {
	ReleaseID      int32   `gorm:"column:release_id;type:integer;primaryKey" json:"release_id"`
	Description    *string `gorm:"column:description;type:text" json:"description"`
	Type           *string `gorm:"column:type;type:character varying(2500)" json:"type"`
	Value          *string `gorm:"column:value;type:text" json:"value"`
	IdentifierHash int64   `gorm:"column:identifier_hash;type:bigint;primaryKey" json:"identifier_hash"` // fnv32 encoded hash from string which is description, type, value appended in order
}

// TableName ReleaseIdentifier's table name
func (*ReleaseIdentifier) TableName() string {
	return TableNameReleaseIdentifier
}
