project_name: go-discogs

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0,GO111MODULE=on]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X cmd.version={{.Version}}
dockers:
  - image_templates:
      - "ghcr.io/goreleaser/go-discogs:{{ .Version }}"
      - "state303/go-discogs:latest"
      - "state303/go-discogs:{{ .Tag }}"
      - "state303/go-discogs:v{{ .Major }}"
      - "state303/go-discogs:v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/state303/go-discogs
      - --label=org.opencontainers.image.source=https://github.com/state303/go-discogs
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
      - --platform=linux/amd64

archives:
  - format: tar.gz
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
nfpms:
  - maintainer: Seunghyun Bosco Bae <state303@dsub.io>
    description: A CLI tool for discogs data batch.
    homepage: https://blog.dsub.io
    license: MIT
    formats:
      - deb
      - rpm
      - apk