project_name: go-discogs

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0,GO111MODULE=on]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X cmd.version={{.Version}}
      
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
nfpms:
  - maintainer: Seunghyun Bosco Bae <state303@dsub.io>
    description: A CLI tool for discogs data batch.
    homepage: https://blog.dsub.io
    license: MIT
    formats:
      - deb
      - rpm
      - apk
